"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['GUI_app.py']
DATA_FILES = []
OPTIONS = {'argv_emulation':True,
'includes': ['opencv', 'tkinter', 'img_modification',],
'strip': True,
'plist': {
'PyRuntimeLocations': [
'@executable_path/../Frameworks.libpython3.7m.dylib',
'/Users/wagatsuma/anaconda/envs/app_make/lib/libpython3.7m.dylib'
]
}}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
